---
channel: stable
apps:
  eink:
    repository: stuart-c/addon-eink
    target: eink
    image: ghcr.io/stuart-c/addon-eink
  llama:
    repository: stuart-c/addon-llama
    target: llama
    image: ghcr.io/stuart-c/addon-llama
