name: "eInk Layout Manager"
version: "0.3.4"
slug: "eink"
image: "ghcr.io/stuart-c/addon-eink"
description: "Manage multiple eInk displays with advanced layouts via OpenDisplay"
url: https://github.com/stuart-c/addon-eink
arch:
  - aarch64
  - amd64
init: false
map:
  - type: media
    read_only: false
panel_icon: "mdi:tablet-dashboard"
panel_title: "eInk Displays"
ingress: true
ingress_port: 8099
host_network: false
hassio_api: true
options:
  log_level: "info"
  media_subdirectory: "eink/scene_display"
schema:
  log_level: "match(^trace|debug|info|notice|warning|error|fatal|critical$)"
  media_subdirectory: "match(^[a-zA-Z0-9_\\-/]+$)"
