name: ik_llama.cpp Server
version: 0.1.8
slug: ik_llama_server
image: ghcr.io/stuart-c/addon-llama
description: High-performance llama.cpp fork for Pi 5
url: https://github.com/stuart-c/addon-llama
arch:
- aarch64
ports:
  8080/tcp: 8080
init: false
options:
  model_url: https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-IQ4_NL.gguf
  ctx_size: 4096
  threads: 4
schema:
  model_url: str
  ctx_size: int
  threads: int
