---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

permissions:
  contents: read

jobs:
  update:
    name: Running updater for ${{ github.event.client_payload.app }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@88408cfe4468560e649cb9c227431a696c9298ea # v2.0.1
        with:
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
